SELECT INFO.REST_ID, INFO.REST_NAME, INFO.FOOD_TYPE, INFO.FAVORITES,INFO.ADDRESS, 
ROUND(AVG(REVIEW.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO INFO
JOIN REST_REVIEW REVIEW ON INFO.REST_ID = REVIEW.REST_ID
GROUP BY REVIEW.REST_ID
HAVING LEFT(INFO.ADDRESS,2) = '서울' 
ORDER BY SCORE DESC, FAVORITES DESC
