SELECT DISTINCT CC.CAR_ID FROM CAR_RENTAL_COMPANY_CAR CC
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CR ON CC.CAR_ID = CR.CAR_ID
WHERE CC.CAR_TYPE = '세단' AND MONTH(CR.START_DATE) >= 10
ORDER BY CC.CAR_ID DESC