SELECT BOARD_ID, WRITER_ID, TITLE, PRICE,
CASE
WHEN UGB.STATUS = 'DONE'
THEN '거래완료'
WHEN UGB.STATUS = 'RESERVED'
THEN '예약중'
WHEN UGB.STATUS = 'SALE'
THEN '판매중'
END AS 'STATUS'
FROM USED_GOODS_BOARD UGB
WHERE DATE_FORMAT(CREATED_DATE,'%Y-%m-%d') = '2022-10-05'
ORDER BY BOARD_ID DESC